ignored = ["github.com/kubeless/kubeless/pkg/functions"]

[[constraint]]
  name = "github.com/dghubble/go-twitter"
  branch = "master"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  branch = "master"
